/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Lab07_Pantallas;

import Lab07_Entidades.Cita;
import Lab07_Entidades.Especialidad;
import Lab07_Entidades.Medico;
import Lab07_Entidades.Paciente;
import javax.swing.ComboBoxModel;
import javax.swing.JFrame;
import laboratorio07.Laboratorio07;

/**
 *
 * @author Frank
 */
public class JFrameCita extends javax.swing.JFrame {

    private JFrameGestorDeCitas padre;
    
    private Cita cita;
    private boolean estoyEditando = false;
    
    private Medico medicoSeleccionado;
    private Paciente pacienteSeleccionado;
    private Especialidad especialidadSeleccionada;
    /**
     * Creates new form JFrameCita
     */
    public JFrameCita(JFrameGestorDeCitas padre) {
        initComponents();
        this.padre = padre;
        
        cbEspecialidad.removeAllItems();
        cbEspecialidad.setEnabled(false);
        
        cbHora.removeAllItems();
        for(String hora: Laboratorio07.horasDisponibles){
            cbHora.addItem(hora);
        }
        
        cbFecha.removeAllItems();
        for(String fecha: Laboratorio07.fechasDisponibles){
            cbFecha.addItem(fecha);
        }
        
    }
    
    public JFrameCita(JFrameGestorDeCitas padre, Cita cita) {
        initComponents();
        this.padre = padre;
        this.cita = cita;
        this.estoyEditando = true;
        this.btnPaciente.setVisible(false);
        this.btnMedico.setVisible(false);
        this.btnGuardar.setVisible(false);
        lblTitulo.setText("Visualizar Cita");
        this.txtMedico.setText(cita.getMedico().getDatosMostrar());
        this.txtPaciente.setText(cita.getPaciente().getDatosMostrar());
        cbEspecialidad.removeAllItems();
        cbEspecialidad.addItem(cita.getEspecialidad().getNombre());
        
        cbFecha.removeAllItems();
        cbFecha.addItem(Laboratorio07.fechasDisponibles.get(cita.getFecha()));
        cbHora.removeAllItems();
        cbHora.addItem(Laboratorio07.horasDisponibles.get(cita.getHora()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        txtPaciente = new javax.swing.JTextField();
        txtMedico = new javax.swing.JTextField();
        cbEspecialidad = new javax.swing.JComboBox<>();
        cbFecha = new javax.swing.JComboBox<>();
        cbHora = new javax.swing.JComboBox<>();
        btnPaciente = new javax.swing.JButton();
        btnMedico = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        lblTitulo.setText("Nueva Cita");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 350, 50));

        txtPaciente.setBackground(new java.awt.Color(153, 204, 255));
        txtPaciente.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        txtPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 390, 60));

        txtMedico.setBackground(new java.awt.Color(153, 204, 255));
        txtMedico.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        jPanel1.add(txtMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 390, 60));

        cbEspecialidad.setBackground(new java.awt.Color(153, 204, 255));
        cbEspecialidad.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        cbEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbEspecialidad.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbEspecialidadPropertyChange(evt);
            }
        });
        jPanel1.add(cbEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 390, 60));

        cbFecha.setBackground(new java.awt.Color(153, 204, 255));
        cbFecha.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        cbFecha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 220, 60));

        cbHora.setBackground(new java.awt.Color(153, 204, 255));
        cbHora.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        cbHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 150, 60));

        btnPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lab07_ImagenesFigma/btnBuscarPaciente.png"))); // NOI18N
        btnPaciente.setBorder(null);
        btnPaciente.setContentAreaFilled(false);
        btnPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 190, 80));

        btnMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lab07_ImagenesFigma/btnBuscarMedico.png"))); // NOI18N
        btnMedico.setBorder(null);
        btnMedico.setContentAreaFilled(false);
        btnMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicoActionPerformed(evt);
            }
        });
        jPanel1.add(btnMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 190, 100));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lab07_ImagenesFigma/btnSalir.png"))); // NOI18N
        btnSalir.setBorder(null);
        btnSalir.setContentAreaFilled(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 190, 80));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lab07_ImagenesFigma/btnCrearCita.png"))); // NOI18N
        btnGuardar.setBorder(null);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 500, 190, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lab07_ImagenesFigma/lblCita.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void guardarCita(){
        
        if (medicoSeleccionado!=null && pacienteSeleccionado!=null){
            int indiceSeleccionado = cbEspecialidad.getSelectedIndex();
            especialidadSeleccionada = medicoSeleccionado.getEspecialidades().get(indiceSeleccionado);
            
            cita = new Cita(medicoSeleccionado, pacienteSeleccionado, especialidadSeleccionada);
            
            cita.setFecha(cbFecha.getSelectedIndex());
            cita.setHora(cbHora.getSelectedIndex());
            
            this.padre.agregarCita(cita);
        }
    }   
        
    public void setPaciente(Paciente paciente){
        this.pacienteSeleccionado = paciente;
        txtPaciente.setText(paciente.getDatosMostrar());
    }
    
    public void setMedico(Medico medico){
        this.medicoSeleccionado = medico;
        txtMedico.setText(this.medicoSeleccionado.getDatosMostrar());
        
        cbEspecialidad.removeAllItems();
        for(Especialidad espec: medico.getEspecialidades()){
            cbEspecialidad.addItem(espec.getNombre());
        }
        
        cbEspecialidad.setEnabled(true);
    }
    
    public void setEspecialidad(Especialidad especialidad){
        this.especialidadSeleccionada = especialidad;
    }
    
        
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

        salir();
        
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        guardarCita();
        salir();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacienteActionPerformed

        JFramePaciente pantallaPacientes =  new JFramePaciente(this);
        pantallaPacientes.setLocationRelativeTo(this);
        pantallaPacientes.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPacienteActionPerformed

    private void btnMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicoActionPerformed

        JFrameMedico pantallaMedicos =  new JFrameMedico(this);
        pantallaMedicos.setLocationRelativeTo(this);
        pantallaMedicos.setVisible(true);
        this.setVisible(false);                             
    }//GEN-LAST:event_btnMedicoActionPerformed

    private void txtPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPacienteActionPerformed

    private void cbEspecialidadPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbEspecialidadPropertyChange

        if(this.medicoSeleccionado!=null){
            Especialidad espec = this.medicoSeleccionado.getEspecialidades().get(cbEspecialidad.getSelectedIndex());
            especialidadSeleccionada = espec;
        }
        
    }//GEN-LAST:event_cbEspecialidadPropertyChange

    private void buscarPaciente(){
        JFramePaciente paciente = new JFramePaciente(this);
        paciente.setLocationRelativeTo(null);
        paciente.setVisible(true);
    }
    
    private void salir(){
        padre.setVisible(true);
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCita(new JFrameGestorDeCitas()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMedico;
    private javax.swing.JButton btnPaciente;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbEspecialidad;
    private javax.swing.JComboBox<String> cbFecha;
    private javax.swing.JComboBox<String> cbHora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtMedico;
    private javax.swing.JTextField txtPaciente;
    // End of variables declaration//GEN-END:variables
}
